jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure that GitHub Actions has write access to the repository contents

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the provided GitHub token
          publish_dir: ./build  # Specify the build directory to deploy
